# Generated by Django 5.2.17 on 2026-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='testimonials/'),
        ),
    ]
