# Generated by Django 5.2.17 on 2026-09-15 13:25

import django.db.models.deletion
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(default=marketing.models.generate_campaign_id, editable=False, help_text='Unique tracking code for this broadcast', max_length=25, unique=True)),
                ('title', models.CharField(help_text="Campaign name e.g. 'October 2026 Tech & AI Outreach'", max_length=200)),
                ('sender_name', models.CharField(default='UniqueTechCamp Solutions', help_text="Sender display name shown in recipients' inbox", max_length=150)),
                ('sender_email', models.EmailField(default='info@uniquetechcamp.org', help_text='From email address', max_length=254)),
                ('default_subject', models.CharField(blank=True, help_text='Fallback subject line if spreadsheet row has no specific subject', max_length=255)),
                ('spreadsheet_file', models.FileField(help_text='Uploaded Excel (.xlsx) or CSV spreadsheet', upload_to='marketing/spreadsheets/')),
                ('delay_seconds', models.FloatField(default=2.0, help_text='Delay between emails in seconds (e.g. 1.0 to 10.0) to comply with SMTP rate limits and avoid spam filters')),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft / Uploaded'), ('sending', 'In Progress / Sending'), ('completed', 'Completed Successfully'), ('failed', 'Encountered Errors')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Email Campaign',
                'verbose_name_plural': 'Bulk Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Recipient's name or title", max_length=150)),
                ('email', models.EmailField(help_text="Recipient's email address", max_length=254)),
                ('subject', models.CharField(help_text='Personalized subject line', max_length=255)),
                ('personalized_message', models.TextField(help_text='Personalized body or message for this contact')),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('sent', 'Sent Successfully'), ('failed', 'Delivery Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error trace if delivery failed')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.bulkcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'ordering': ['id'],
            },
        ),
    ]
