# Generated by Django 5.2.17 on 2026-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_choice', models.CharField(choices=[('email1', 'Email 1: info@uniquetechcamp.org (Primary)'), ('email2', 'Email 2: UniqueTechCamp@gmail.com (Alternative - Google App Password)')], default='email1', help_text='Email account used for sending', max_length=20)),
                ('from_email', models.CharField(help_text='From address header', max_length=255)),
                ('to_email', models.EmailField(help_text="Recipient's email address", max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text="Recipient's name", max_length=150)),
                ('subject', models.CharField(help_text='Subject line', max_length=255)),
                ('body_text', models.TextField(blank=True, help_text='Plain text email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML formatted email body')),
                ('attachment', models.FileField(blank=True, help_text='Attached file (e.g. PDF, Document, Image)', null=True, upload_to='marketing/attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, help_text='Original attachment filename', max_length=255)),
                ('email_type', models.CharField(choices=[('single', 'Single / Custom Email'), ('welcome', 'Welcome Email'), ('campaign', 'Marketing Campaign'), ('appointment', 'Appointment Booking'), ('contact', 'Contact Form Autoresponder'), ('system', 'System Notification')], default='single', help_text='Category of this email', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('sent', 'Sent Successfully'), ('failed', 'Delivery Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of resend attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='sender_choice',
            field=models.CharField(choices=[('email1', 'Email 1: info@uniquetechcamp.org (Primary)'), ('email2', 'Email 2: UniqueTechCamp@gmail.com (Alternative)')], default='email1', help_text='Choose which email account to send from', max_length=20),
        ),
    ]
