# Generated by Django 5.2.17 on 2026-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_emaillog_bulkcampaign_sender_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='email_format',
            field=models.CharField(choices=[('branded', 'UniqueTechCamp Branded (Top Logo + 9 Social Channels + Support Box)'), ('welcome', 'Official High-Converting Welcome Email Layout'), ('plain', 'Clean Direct Message (Minimalist Text)')], default='branded', help_text='Email layout template to wrap broadcast messages', max_length=20),
        ),
    ]
