# Generated by Django 5.2.17 on 2026-09-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_bulkcampaign_email_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppressionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Suppressed email address', max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce (550 Mailbox Does Not Exist)'), ('invalid_domain', 'Invalid / Dead Domain (No MX Records)'), ('spam_trap', 'Spam Trap / Blacklist Hazard'), ('disposable', 'Disposable / Temporary Email'), ('unsubscribed', 'Recipient Unsubscribed'), ('manual_block', 'Manually Blocked by Admin')], default='hard_bounce', help_text='Reason for suppression', max_length=30)),
                ('detail', models.TextField(blank=True, help_text='Error message or source of suppression')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Suppressed Email',
                'verbose_name_plural': 'Suppression List',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='is_deliverable',
            field=models.BooleanField(default=True, help_text='Whether this contact is safe to send to without risking reputation'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='verification_reason',
            field=models.CharField(blank=True, help_text='Verification check result or reason', max_length=255),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified Clean'), ('risky', 'Risky / Role-Based'), ('invalid', 'Invalid / Dead Domain'), ('suppressed', 'Suppressed / Bounced')], db_index=True, default='unverified', help_text='Deliverability score from pre-send verification shield', max_length=20),
        ),
    ]
