# Generated by Django 5.2.17 on 2026-09-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL (e.g. Unsplash, CDN)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(help_text='Google Material Symbol name (e.g. language, hiking, volunteer_activism)', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='services/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL', max_length=500, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional title or caption for this visual', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
