# Generated by Django 5.2.17 on 2026-09-18 03:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='International format starting with country code e.g. +254715479955', max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must start with a valid international country code (e.g., +254712345678 or +1234567890).', regex='^\\+[1-9]\\d{7,14}$')])),
                ('country_code', models.CharField(blank=True, default='+254', max_length=8)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Designates whether this client has verified their email address.')),
                ('email_verification_token', models.CharField(blank=True, default=uuid.uuid4, help_text='Secure cryptographic verification token', max_length=64)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_prompts', models.ManyToManyField(blank=True, help_text='Prompts saved or bookmarked by this client', related_name='favorited_by_profiles', to='ai_prompts.aiprompt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
