# Generated by Django 5.2.17 on 2026-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL (e.g. Unsplash, CDN)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='blog/'),
        ),
    ]
