# Generated by Django 5.2.17 on 2026-09-18 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('tagline', models.CharField(help_text='Catchy 1-sentence value proposition', max_length=300)),
                ('overview', models.TextField(help_text='Detailed project description, architecture overview, and what gets built')),
                ('master_prompt', models.TextField(help_text='The DETAILED AI MASTER CODING PROMPT ready to paste into Claude Code, Cursor, Windsurf, etc.')),
                ('system_instructions', models.TextField(blank=True, help_text='Step-by-step instructions on executing the prompt in AI tools')),
                ('features_list', models.TextField(blank=True, help_text='Bulleted list of key system features (1 feature per line)')),
                ('prerequisites', models.TextField(blank=True, help_text='Accounts, APIs, or tools needed (e.g. Google Cloud, Node.js, Claude API key)')),
                ('tech_stack', models.CharField(default='Google Apps Script, Claude Code, HTML5, Tailwind CSS', help_text='Comma-separated tech stack badges', max_length=255)),
                ('target_ai_tools', models.CharField(default='Claude Code, Cursor, Windsurf, ChatGPT-4o, Gemini', help_text='Tools optimized for this prompt', max_length=255)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Master', 'Master / Enterprise')], default='Intermediate', max_length=20)),
                ('is_free', models.BooleanField(default=False, help_text='Check if prompt is 100% free to copy and download')),
                ('price_kes', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in Kenya Shillings (KES)', max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in US Dollars (USD)', max_digits=10)),
                ('assistance_price_kes', models.DecimalField(decimal_places=2, default=2500.0, help_text='1-on-1 personalized setup & customization fee (KES)', max_digits=10)),
                ('assistance_price_usd', models.DecimalField(decimal_places=2, default=25.0, help_text='1-on-1 personalized setup & customization fee (USD)', max_digits=10)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL or embed link (e.g. https://www.youtube.com/watch?v=...)', null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='prompts/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('copy_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Master Coding Prompt',
                'verbose_name_plural': 'AI Master Coding Prompts',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='code', help_text='Lucide or Material icon name e.g. code, table, bot, shopping-bag, layout', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prompt Category',
                'verbose_name_plural': 'Prompt Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptAssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(help_text='Phone number starting with country code e.g. +254...', max_length=30)),
                ('requirements', models.TextField(help_text='Describe what customizations, features, or setup help you need')),
                ('mpesa_reference', models.CharField(blank=True, help_text='M-Pesa transaction reference from Till 5797853', max_length=50, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress / Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='ai_prompts.aiprompt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_assistance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Assistance Request',
                'verbose_name_plural': 'Prompt Assistance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiprompt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='ai_prompts.promptcategory'),
        ),
    ]
