# Generated by Django 5.2.17 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
