# Generated by Django 5.2.17 on 2026-09-18 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_prompts', '0002_alter_aiprompt_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(help_text='WhatsApp / Phone number starting with country code e.g. +254...', max_length=35)),
                ('payment_method', models.CharField(choices=[('mpesa_till', 'Safaricom M-Pesa Till 5797853'), ('mpesa_screenshot', 'M-Pesa Screenshot / Receipt Upload'), ('bank_transfer', 'Bank Transfer / Wire'), ('paypal_card', 'PayPal / Card Payment'), ('other', 'Other Payment Request')], default='mpesa_till', max_length=40)),
                ('transaction_code', models.CharField(blank=True, help_text='M-Pesa Transaction Code (e.g., UII9O6P15V) or Reference', max_length=80, null=True)),
                ('payment_message', models.TextField(blank=True, help_text='Full pasted M-Pesa SMS confirmation message or transaction notes')),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Screenshot of M-Pesa message or payment receipt', null=True, upload_to='prompt_payments/%Y/%m/')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved / Verified (Access Granted)'), ('rejected', 'Rejected / Invalid Reference')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Tick to approve and immediately unlock prompt access for this client')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_email_sent', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by management/admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ai_prompts.aiprompt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Payment & Access Order',
                'verbose_name_plural': 'Prompt Payments & Access Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
