# Generated by Django 5.2.17 on 2026-09-18 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('exploring', 'Initial Exploring'), ('lead_captured', 'Lead Captured & Qualified'), ('booking_initiated', 'Consultation Booking Initiated'), ('appointment_booked', 'Appointment Booked'), ('concluded', 'Session Concluded')], default='exploring', max_length=30)),
                ('pending_query', models.TextField(blank=True, help_text='Client inquiry preserved while contact information is being requested and validated')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Logged in client account if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Prospective Client'), ('assistant', 'UniqueTechCamp AI Assistant'), ('system', 'System / Action Event')], max_length=20)),
                ('message', models.TextField()),
                ('model_used', models.CharField(blank=True, help_text='Exact Gemini model that fulfilled this turn (e.g. gemini-2.5-flash, gemini-2.0-flash)', max_length=100)),
                ('is_fallback', models.BooleanField(default=False, help_text='Indicates if this response was generated via a fallback model due to rate limit or quota interception')),
                ('action_type', models.CharField(choices=[('normal', 'Standard Conversational Turn'), ('lead_form', 'Interactive Lead Capture Form'), ('slot_picker', 'Consultation Time-Slot Discovery Picker'), ('booking_card', 'Confirmed Appointment Summary Card')], default='normal', help_text='Type of special interactive card rendered alongside this message', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured payloads e.g. slot choices, booking details, lead capture fields, or diagnostic logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Prospective client's full name", max_length=150)),
                ('email', models.EmailField(help_text='Verified client email address', max_length=254)),
                ('phone', models.CharField(help_text='WhatsApp or phone number with international country code (e.g. +254...)', max_length=50)),
                ('industry', models.CharField(blank=True, help_text="Client's industry or business niche", max_length=120)),
                ('business_bottleneck', models.TextField(blank=True, help_text='Current bottleneck or business challenge identified')),
                ('preferred_timeline', models.CharField(blank=True, help_text='Desired delivery timeline or target launch date', max_length=100)),
                ('budget_or_scope', models.CharField(blank=True, help_text='Project scale, scope tier, or budget signal', max_length=120)),
                ('qualification_notes', models.TextField(blank=True, help_text='Automated or architectural notes from conversation scoping')),
                ('transcript_sent', models.BooleanField(default=False, help_text='Whether the branded conversation transcript was emailed to client')),
                ('transcript_sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_alert_sent', models.BooleanField(default=False, help_text='Whether real-time high priority alert was dispatched to admin desk')),
                ('admin_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_appointment', models.OneToOneField(blank=True, help_text='Consultation appointment scheduled during or subsequent to the AI session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_lead_source', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'AI Captured Lead',
                'verbose_name_plural': 'AI Captured Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Captured prospect profile linked to this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='ai_assistant.leadcapture'),
        ),
    ]
