# Generated by Django 5.2.17 on 2026-09-15 13:16

import appointments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_image_url_alter_service_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default=appointments.models.generate_booking_reference, editable=False, help_text='Unique reference code for client tracking & calendar sync', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Client's full name", max_length=150)),
                ('email', models.EmailField(help_text='Official email address for calendar invite & confirmation', max_length=254)),
                ('phone', models.CharField(help_text='Direct phone or WhatsApp number with country code', max_length=40)),
                ('company_name', models.CharField(blank=True, help_text='Company, startup, or organization name (optional)', max_length=150)),
                ('preferred_date', models.DateField(help_text='Requested date for the consultation session')),
                ('preferred_time_slot', models.CharField(choices=[('09:00 - 10:00', '09:00 AM - 10:00 AM (EAT / UTC+3)'), ('10:30 - 11:30', '10:30 AM - 11:30 AM (EAT / UTC+3)'), ('12:00 - 13:00', '12:00 PM - 01:00 PM (EAT / UTC+3)'), ('14:00 - 15:00', '02:00 PM - 03:00 PM (EAT / UTC+3)'), ('15:30 - 16:30', '03:30 PM - 04:30 PM (EAT / UTC+3)'), ('17:00 - 18:00', '05:00 PM - 06:00 PM (EAT / UTC+3)')], default='10:30 - 11:30', help_text='Preferred 1-hour consultation window', max_length=50)),
                ('meeting_type', models.CharField(choices=[('google_meet', 'Google Meet (Recommended Video Call)'), ('whatsapp_call', 'WhatsApp Video / Audio Call'), ('phone', 'Direct Phone Call'), ('office', 'In-Person at Nairobi CBD Office (Kenya)')], default='google_meet', help_text='Preferred platform for the consultation', max_length=30)),
                ('project_description', models.TextField(help_text='Summary of business goals, technical requirements, or specific challenges')),
                ('status', models.CharField(choices=[('pending', 'Pending Review & Confirmation'), ('confirmed', 'Confirmed & Scheduled'), ('completed', 'Session Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current booking workflow status', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Google Meet or conference link assigned by UniqueTechCamp', max_length=500, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from the engineering & solutions architecture team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, help_text='The specific digital solution requested, or empty for general consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Consultation Appointment',
                'verbose_name_plural': 'Consultation Appointments',
                'ordering': ['-preferred_date', '-created_at'],
            },
        ),
    ]
