# Generated by Django 5.2.17 on 2026-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('web_form', 'Standard Web Booking Form'), ('ai_assistant', 'AI Conversational Assistant'), ('whatsapp_direct', 'Direct WhatsApp Desk'), ('admin_manual', 'Admin Manual Entry')], default='web_form', help_text='Channel / origin where the consultation booking was initiated', max_length=40),
        ),
    ]
