# Generated by Django 5.2.17 on 2026-09-15 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the project was developed / completed'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL (e.g. Unsplash, CDN)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectscreenshot',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an external image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(help_text='Client or organization name', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='portfolio/featured/'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file from computer', null=True, upload_to='portfolio/screenshots/'),
        ),
    ]
